app:
  envs:
    SSO_AUTH: "https://auth.gas.apps.dev.devsun.ru"
    NSI_REGISTRY_HOST: "https://gas.apps.dev.devsun.ru/service/registry/nsi"
    WORKFLOW_MANAGER_HOST: "https://gas.apps.dev.devsun.ru/service/zeebe/manager"
    META_REGISTRY_HOST: "https://gas.apps.dev.devsun.ru/service/registry/meta"
    COMMISSIONS_REGISTRY_HOST: 'https://gas.apps.dev.devsun.ru/service/registry/commission'
    FIAS_SERVICE_HOST: "https://gas.apps.dev.devsun.ru/service/fias"
    JOURNAL_REGISTRY_HOST: "https://gas.apps.dev.devsun.ru/service/registry/journal"
    CAMPAIGN_REGISTRY_HOST: "https://gas.apps.dev.devsun.ru/service/registry/campaign/election"
    CANDIDATE_REGISTRY_HOST: "https://gas.apps.dev.devsun.ru/service/registry/candidate"
    NOTIFIER_GATEWAY: "wss://gas.apps.dev.devsun.ru/service/notifier/gateway"
    S3_URL_SIGNER: "https://gas.apps.dev.devsun.ru/service/s3urlsigner"
    USERTASK_REGISTRY_HOST: "https://gas.apps.dev.devsun.ru/service/registry/usertask"
    GAS_HOST: "https://gas.apps.dev.devsun.ru"
    APOLLO_SERVER_HOST: "https://gas.apps.dev.devsun.ru/service/graphql-federation/gateway"
