app:
  containers:
  - image:
      repo: docker.devsun.ru
      name: dev/shell-nsi
      tag: "1.0.0"
    ports:
    - number: 80
      name: http
    name: shell-nsi
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "200m"
        memory: "500Mi"
  external:
    enabled: true
    enableWebSocket: true
    path: /shell
    annotations:
      nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.arm.gas.apps.dev.devsun.ru"
  envs:
    SSO_AUTH: "{{ SSO_AUTH }}" #Адрес сервиса SSO
    SSO_UI: "{{ SSO_UI }}" #Адрес пользовательского инетрфейса SSO
    AUTH_DOMAIN: "{{ AUTH_DOMAIN }}"
    MF_AUTH: "{{ MF_AUTH }}"
    MF_NSI_HANDBOOKS: "{{ MF_NSI_HANDBOOKS }}"
    MF_CAMPAIGNS: "{{ MF_CAMPAIGNS }}"
    MF_COMMISSIONS: "{{ MF_COMMISSIONS }}"
    MF_PAIP_LAW: "{{ MF_PAIP_LAW }}"
    MF_PAIP_CALENDAR: "{{ MF_PAIP_CALENDAR }}"
    MF_PAIP_CERTIFICATE: "{{ MF_PAIP_CERTIFICATE }}"
    MF_CANDIDATES: "{{ MF_CANDIDATES }}"
    MF_TVD: "{{ MF_TVD }}"
    PAIP_LAW_REGISTRY_HOST: "{{ PAIP_LAW_REGISTRY_HOST }}"
    PAIP_CALENDAR_REGISTRY_HOST: "{{ PAIP_CALENDAR_REGISTRY_HOST }}"
    PAIP_CERTIFICATE_REGISTRY_HOST: "{{ PAIP_CERTIFICATE_REGISTRY_HOST }}"
    NSI_REGISTRY_HOST: "{{ NSI_REGISTRY_HOST }}"
    WORKFLOW_MANAGER_HOST: "{{ WORKFLOW_MANAGER_HOST }}"
    META_REGISTRY_HOST: "{{ META_REGISTRY_HOST }}"
    FIAS_SERVICE_HOST: "{{ FIAS_SERVICE_HOST }}"
    JOURNAL_REGISTRY_HOST: "{{ JOURNAL_REGISTRY_HOST }}"
    NOTIFIER_GATEWAY: "{{ NOTIFIER_GATEWAY }}"
    S3_URL_SIGNER: "{{ S3_URL_SIGNER }}"
    FORMAT_CONVERTER: "{{ FORMAT_CONVERTER }}"
    USERTASK_REGISTRY_HOST: "{{ USERTASK_REGISTRY_HOST }}"
    ADDRESS_REGISTRY_HOST: "{{ ADDRESS_REGISTRY_HOST }}"
    ADDRESS_SEARCH_NODE_HOST: "{{ ADDRESS_SEARCH_NODE_HOST }}"
    CAMPAIGN_REGISTRY_HOST: "{{ CAMPAIGN_REGISTRY_HOST }}"
    COMMISSIONS_REGISTRY_HOST: "{{COMMISSIONS_REGISTRY_HOST}}"
    CANDIDATE_REGISTRY_HOST: "{{ CANDIDATE_REGISTRY_HOST }}"
    COMMISSION_MEMBER_REGISTRY_HOST: "{{ COMMISSION_MEMBER_REGISTRY_HOST }}"
    TERRITORY_REGISTRY_HOST: "{{ TERRITORY_REGISTRY_HOST }}"
    RESULTS_REGISTRY_HOST: "{{ RESULTS_REGISTRY_HOST }}"
    ROLE_REGISTRY_HOST: "{{ ROLE_REGISTRY_HOST }}"
    APOLLO_SERVER_HOST: "{{ APOLLO_SERVER_HOST }}"
    APP_PROJECT_PATH: "{{ APP_PROJECT_PATH }}"
    AUTH_CLIENT_ID: "{{ AUTH_CLIENT_ID }}"
    AUTH_CLIENT_SECRET: "{{ AUTH_CLIENT_SECRET }}"
    AUTH_SCOPE: "{{ AUTH_SCOPE }}"

monitoring:
  group: gas
  project: GAS_PAIP

features:
  static:
    enabled: true
    params:
      - sso
